### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by liamdawson** [sharkdp/pastel#70] opened 2019-08-26 05:50 UTC
I'd love to install pastel via Homebrew, so I've [opened a PR](https://github.com/Homebrew/homebrew-core/pull/43459) to the core formula repo. If it's not accepted, it'd be great if you could pull that formula into a tap yourself?

Opening this as an issue to prevent duplicates... hopefully :)

**Comment by sharkdp** [comment] 2019-08-26 05:54
Thank you very much!

I don't know much about Homebrew and I don't really want to personally manage packages for operating systems which I have no access to. That being said, I'd be very happy to include the install instructions in the README, once the PR is merged.

**Comment by liamdawson** [comment] 2019-08-26 05:56
Homebrew is now compatible with Linux too, so you can test it on half of the environments, at minimum.

https://docs.brew.sh/Homebrew-on-Linux

(That's part of the reason I love it now—use most of the same packages on my personal Linux laptop and work Macbook!)

**Comment by davinkevin** [comment] 2019-08-29 06:21
Since the release of hombrew for linux, I see a huge part of linux users (around me) using brew, so 👍for this one

**Comment by BarryMode** [comment] 2019-08-31 03:06
Definitely interested in installing via brew. Loving what pastel has to offer for color!

**Comment by liamdawson** [comment] 2019-09-16 11:22
0.5.3 is in homebrew now! https://github.com/Homebrew/homebrew-core/pull/43459#issuecomment-531700348

**Closed** 2019-09-16 11:22 UTC
Labels: packaging / tooling

**Comment by sharkdp** [comment] 2019-09-16 17:16
Thank you. I added instructions to the README (which are hopefully correct).

**Comment by BarryMode** [comment] 2019-09-16 19:10
Confirmed, TY!

```
➜  ~ brew install pastel
==> Downloading https://homebrew.bintray.com/bottles/pastel-0.5.3.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/cd/cd35a70df7798441446d2494d45be08844bfc261d3235d8b9a
######################################################################## 100.0%
==> Pouring pastel-0.5.3.mojave.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/pastel/0.5.3: 8 files, 2.3MB
```
